extends Node


var prefix_words = [
				"Dire", 
				"Blue", 
				"Red", 
				"White", 
				"Bitten", 
				"Woven", 
				"Spiral", 
				"Jovial", 
				"Sprung", 
				"Bionic", 
				"Zomboid", 
				"Wimpering", 
				"Bearded", 
				"Sampled", 
				"Morbid", 
				"Scorched", 
				"Seared", 
				"Flaming", 
				"Frozen", 
				"Chilled", 
				"Bitter", 
				"Salty", 
				"Panicked", 
				"Angry", 
				"Branded", 
				"Doused", 
				"Demonic", 
				"Glimmering", 
				"Starry", 
				"Loathe", 
				"Spiny", 
				"Chimeral", 
				"Vampiric", 
				"Defiled", 
				"Warm", 
				"Cool", 
				"Catlike", 
				"Venomous", 
				"Worn", 
				"Ringed", 
				"Aspirant's", 
				"Ogre's", 
				"Goblin's", 
]

var suffix_words = [
				"Ghoul", 
				"Rain", 
				"Snow", 
				"Potato", 
				"Germ", 
				"Rock", 
				"Eagle", 
				"Ape", 
				"Eyes", 
				"Heart", 
				"Lungs", 
				"Liver", 
				"Brain", 
				"Wolf", 
				"Fox", 
				"Vagabond", 
				"Thorn", 
				"Reaver", 
				"Flesh", 
				"Meat", 
				"Wind", 
				"Fear", 
				"Bane", 
				"Ogre", 
				"Giant", 
				"Crux", 
				"Tiara", 
				"Seal", 
				"Cup", 
				"Statue", 
				"Key", 
				"Crown", 
				"Mask", 
				"Jar"
]

func generate_name():
				var word_one = prefix_words[randi() % len(prefix_words)]
				var word_two = suffix_words[randi() % len(suffix_words)]

				return word_one + " " + word_two
