extends Node
class_name MonsterTypes

const MonsterType = {
				"SKELETON_ARCHER": "SKELETON_ARCHER", 
				"SKELETON_CURSER": "SKELETON_CURSER", 
				"TRAINING_DUMMY": "TRAINING_DUMMY", 
				"SKELETON_WARRIOR": "SKELETON_WARRIOR", 
				"SKELETON_MAGE": "SKELETON_MAGE", 
				"ATTACK_DOG": "ATTACK_DOG", 
				"LIGHTNING_DOG": "LIGHTNING_DOG", 
				"FIRE_BOMBER": "FIRE_BOMBER", 
				"CHILLED_BONES": "CHILLED_BONES", 
				"SKELETON_SPARKER": "SKELETON_SPARKER", 
				"SKELETOR": "SKELETOR", 
				"ZOMBIE": "ZOMBIE", 
				"SPIDER": "SPIDER", 
				"NINJA": "NINJA", 
				"ICE_GOLEM": "ICE_GOLEM", 
				"BOSS_GATEKEEPER": "BOSS_GATEKEEPER", 
				"BOSS_SLUDGE": "BOSS_SLUDGE", 
				"BOSS_SPIRIT_OF_THE_ANCIENT": "BOSS_SPIRIT_OF_THE_ANCIENT", 
				"BOSS_MUTATED_SPIDER": "BOSS_MUTATED_SPIDER", 
}
