from pathlib import Path
import hashlib, struct, zlib

repo = Path(r"C:\AI-GAME\Mutagenic-zhCN-HD")
product = repo / "product"
sprites = product / "sprites"
mapped = sprites / "_mapped"
placeholders = sprites / "_placeholders"

BUCKET_COLORS = {
    "skills": (106, 79, 191),
    "status": (63, 163, 77),
    "affixes": (200, 162, 39),
    "equipment": (176, 101, 58),
    "items": (79, 134, 192),
    "ui": (154, 160, 166),
    "actors": (200, 80, 80),
    "tiles": (91, 140, 90),
    "vfx": (176, 95, 200),
    "other": (128, 128, 128),
}

def placeholder_colors(bucket: str, stem: str):
    base = BUCKET_COLORS.get(bucket, BUCKET_COLORS["other"])
    digest = hashlib.md5(stem.encode("utf-8")).digest()
    jitter = tuple((digest[i] % 41) - 20 for i in range(3))
    fill = tuple(max(0, min(255, c + j)) for c, j in zip(base, jitter))
    border = tuple(max(0, min(255, int(c * 0.45))) for c in base)
    return fill, border

def write_png(path: Path, width: int, height: int, fill, border, border_px=2):
    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))
    rows = []
    for y in range(height):
        row = bytearray(b"\x00")
        for x in range(width):
            edge = x < border_px or y < border_px or x >= width - border_px or y >= height - border_px
            row += bytes(border if edge else fill)
        rows.append(bytes(row))
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) + chunk(b"IEND", b""))
    path.write_bytes(png)

targets = [
    ("actors", "attack_dog"),
    ("actors", "dragon"),
    ("actors", "dragon_wings"),
    ("actors", "chilled_bones"),
    ("actors", "frozen_boots"),
    ("actors", "lightning_dog"),
    ("actors", "spirit_of_the_ancient"),
    ("tiles", "map_highlighted"),
]

for bucket, stem in targets:
    p = mapped / bucket / f"{stem}.png"
    imp = Path(str(p) + ".import")
    if p.is_file():
        p.unlink()
        print(f"deleted {p}")
    else:
        print(f"not found {p}")
    if imp.is_file():
        imp.unlink()
        print(f"deleted {imp}")
    # ensure placeholder
    ph = placeholders / bucket / f"{stem}.png"
    ph.parent.mkdir(parents=True, exist_ok=True)
    if not ph.is_file():
        fill, border = placeholder_colors(bucket, stem)
        write_png(ph, 64, 64, fill, border)
        print(f"created placeholder {ph}")
    else:
        print(f"placeholder exists {ph}")
    # ensure .import? do we need import? For placeholders, original has .import too? Let's see placeholders had .import earlier listing: yes each placeholder had .import. But we generate PNG only; Godot will generate import on next scan. Could keep existing .import if placeholder already existed? For new placeholders we created, there is no .import yet. But we should maybe not worry; art_map.py previously generates placeholder PNG without .import? Actually placeholders generated by art_map.py are just PNGs, but existing placeholders have .import because Godot imported them. Our newly created ones won't have .import until editor scan, but that's fine. We'll leave.
    # also ensure if dragon placeholder should be checked
    # also need to ensure _placeholders/actors/dragon.png for shared case? Already.

# List resulting
print("--- mapped remaining ---")
for bucket, stem in targets:
    print(bucket, stem, "exists mapped:", (mapped / bucket / f"{stem}.png").exists(), "placeholder:", (placeholders / bucket / f"{stem}.png").exists())
