extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "impl_ailment_avoidance", 
												"stat": "ailment_avoidance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 4, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 

								
								{
												"id": "spreading_flames_proliferate", 
												"keystone": "UNIQUE_SPREADING_FLAMES", 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "spreading_flames_damage", 
												"stat": "fire_damage", 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.4, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "spreading_flames_fire_ailment", 
												"stat": "fire_ailment_chance", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.2, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "spreading_flames_fire_resistance", 
												"stat": "fire_resistance", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.4, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 

								
								{
												"id": "balance_of_power_keystone", 
												"keystone": "UNIQUE_BALANCE_OF_POWER", 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "balance_of_power_life", 
												"stat": "health_max", 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.2, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
				]

				
				mod_option_configs.append_array(
								CommonAmuletMods.mod_option_configs.duplicate(true)
				)
				compile()
