extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								
								{
												"id": "impl_physical_damage_flat", 
												"stat": "physical_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_lightning_damage_flat", 
												"stat": "lightning_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_cold_damage_flat", 
												"stat": "cold_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_fire_damage_flat", 
												"stat": "fire_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_toxic_damage_flat", 
												"stat": "toxic_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_more_damage", 
												"stat": "all_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.05, 
												"step": 1.78, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 50, 
												"unique": false, 
								}, 


								
								{
												"id": "physical_damage_flat", 
												"stat": "physical_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
												"group_id": "flat_damage", 
								}, 
								{
												"id": "lightning_damage_flat", 
												"stat": "lightning_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
												"group_id": "flat_damage", 
								}, 
								{
												"id": "cold_damage_flat", 
												"stat": "cold_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
												"group_id": "flat_damage", 
								}, 
								{
												"id": "fire_damage_flat", 
												"stat": "fire_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
												"group_id": "flat_damage", 
								}, 
								{
												"id": "toxic_damage_flat", 
												"stat": "toxic_damage", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 3, 
												"step": 1.78, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
												"group_id": "flat_damage", 
								}, 
								{
												"id": "projectile_speed", 
												"stat": "projectile_speed", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.12, 
												"step": 1.6, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "crit_chance_spells", 
												"stat": "crit_chance", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 1.45, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "radius_spells", 
												"stat": "radius", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1.0, 
												"step": 1.5, 
												"stepified": 0.1, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
				]

				mod_option_configs.append_array(
								CommonWeaponMods.mod_option_configs.duplicate(true)
				)

				compile()
