#!/usr/bin/env python3
"""Generate C5-L10: FULL skill tree (53 skills + 60 supports) name/description translations.

Each unit old_text/new_text = the full serialized field line (unique in file).
Translations follow the zh_CN glossary (docs/zh_CN_glossary.md).
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "mods/c5-l10-skills-tree-zhcn/mod.json"

# ---- translation table: (file, line_no, old_line, new_line, source_text, translation) ----
# Skills.gd entries: name then description per skill
SKILLS = [
    # (line_name, old_name, new_name, src_name, tr_name, line_desc, old_desc, new_desc, src_desc, tr_desc)
    (181, '"name": "Lava Orb",', '"name": "熔岩弹",', "Lava Orb", "熔岩弹",
     182, '"description": "Cast a ball of magma at a nearby enemy, with a chance to set them on fire.",',
     '"description": "向附近敌人掷出一枚熔岩球，有几率使其燃烧。",',
     "Cast a ball of magma at a nearby enemy, with a chance to set them on fire.",
     "向附近敌人掷出一枚熔岩球，有几率使其燃烧。"),
    (201, '"name": "Chain Lightning",', '"name": "连锁闪电",', "Chain Lightning", "连锁闪电",
     202, '"description": "Cast a surge of lightning towards an enemy, chaining to multiple enemies.",',
     '"description": "向敌人释放一道闪电冲击，可连锁命中多个敌人。",',
     "Cast a surge of lightning towards an enemy, chaining to multiple enemies.",
     "向敌人释放一道闪电冲击，可连锁命中多个敌人。"),
    (211, '"name": "Lightning Spear",', '"name": "闪电长矛",', "Lightning Spear", "闪电长矛",
     212, '"description": "Throw a spear of pure lightning, inflicting powerful Lightning ailments. If Lightning Spear hits an enemy affected by Jolt, it will consume the Jolt to deal 200% of the Jolts effect as More Damage.",',
     '"description": "投掷一杆纯粹闪电构成的长矛，造成强力闪电异常状态。若闪电长矛命中受电击影响的敌人，将消耗其电击效果，以其 200% 的效果造成更多伤害。",',
     "Throw a spear of pure lightning, inflicting powerful Lightning ailments. If Lightning Spear hits an enemy affected by Jolt, it will consume the Jolt to deal 200% of the Jolts effect as More Damage.",
     "投掷一杆纯粹闪电构成的长矛，造成强力闪电异常状态。若闪电长矛命中受电击影响的敌人，将消耗其电击效果，以其 200% 的效果造成更多伤害。"),
    (221, '"name": "Flame Tether",', '"name": "火焰锁链",', "Flame Tether", "火焰锁链",
     222, '"description": "Tether yourself to nearby enemies, dealing damage to them. Enemies affected by Flame Tethers deal 25% Less Damage.",',
     '"description": "用锁链连接附近敌人并对其造成伤害。受火焰锁链影响的敌人造成 25% 更少伤害。",',
     "Tether yourself to nearby enemies, dealing damage to them. Enemies affected by Flame Tethers deal 25% Less Damage.",
     "用锁链连接附近敌人并对其造成伤害。受火焰锁链影响的敌人造成 25% 更少伤害。"),
    (231, '"name": "Lava Surge",', '"name": "熔岩喷涌",', "Lava Surge", "熔岩喷涌",
     232, '"description": "Channel a stream of Lava towards a nearby enemy, dealing massive Fire damage in an area.",',
     '"description": "向附近敌人引导一股熔岩流，在区域内造成大量火焰伤害。",',
     "Channel a stream of Lava towards a nearby enemy, dealing massive Fire damage in an area.",
     "向附近敌人引导一股熔岩流，在区域内造成大量火焰伤害。"),
    (241, '"name": "Doom Tether",', '"name": "厄运锁链",', "Doom Tether", "厄运锁链",
     242, '"description": "Tether yourself to nearby enemies, periodically causing damage. If the enemy is cursed, then Doom Tether will deal 50% More Damage for each Curse on the enemy, and deal damage in an area.",',
     '"description": "用锁链连接附近敌人并周期性造成伤害。若敌人受到诅咒，厄运锁链将根据其身上的每个诅咒造成 50% 更多伤害，并在区域内造成伤害。",',
     "Tether yourself to nearby enemies, periodically causing damage. If the enemy is cursed, then Doom Tether will deal 50% More Damage for each Curse on the enemy, and deal damage in an area.",
     "用锁链连接附近敌人并周期性造成伤害。若敌人受到诅咒，厄运锁链将根据其身上的每个诅咒造成 50% 更多伤害，并在区域内造成伤害。"),
    (251, '"name": "Frost Orb",', '"name": "冰霜弹",', "Frost Orb", "冰霜弹",
     252, '"description": "Cast a ball of ice at a nearby enemy. Deals 25% splash damage. Frost Orb cannot pierce or chain.",',
     '"description": "向附近敌人掷出一枚冰球，造成 25% 溅射伤害。冰霜弹无法穿透或连锁。",',
     "Cast a ball of ice at a nearby enemy. Deals 25% splash damage. Frost Orb cannot pierce or chain.",
     "向附近敌人掷出一枚冰球，造成 25% 溅射伤害。冰霜弹无法穿透或连锁。"),
    (261, '"name": "Icy Shard Burst",', '"name": "寒冰碎片迸发",', "Icy Shard Burst", "寒冰碎片迸发",
     262, '"description": "Cast a volatile ball of ice at a nearby enemy, which releases shards in random directions, having a high chance to Freeze. Extra projectiles affect the number of released shards. Shards cannot pierce or chain.",',
     '"description": "向附近敌人掷出一枚不稳定的冰球，向随机方向迸发碎片，有较高几率冻结敌人。额外投射物会增加迸发的碎片数量。碎片无法穿透或连锁。",',
     "Cast a volatile ball of ice at a nearby enemy, which releases shards in random directions, having a high chance to Freeze. Extra projectiles affect the number of released shards. Shards cannot pierce or chain.",
     "向附近敌人掷出一枚不稳定的冰球，向随机方向迸发碎片，有较高几率冻结敌人。额外投射物会增加迸发的碎片数量。碎片无法穿透或连锁。"),
    (271, '"name": "Static Charges",', '"name": "静电电荷",', "Static Charges", "静电电荷",
     272, '"description": "Cast statically charged particles around you. Charges cannot Chain.",',
     '"description": "在你周围释放带静电的粒子。电荷无法连锁。",',
     "Cast statically charged particles around you. Charges cannot Chain.",
     "在你周围释放带静电的粒子。电荷无法连锁。"),
    (281, '"name": "Vesuvius",', '"name": "维苏威火山",', "Vesuvius", "维苏威火山",
     282, '"description": "A volcanic eruption spews orbs of magma which explode after a short delay, damaging nearby enemies. Cast speed increases the rate of magma orbs spewing.",',
     '"description": "火山喷发涌出熔岩球，短暂延迟后爆炸，伤害附近敌人。施法速度提高熔岩球的喷涌频率。",',
     "A volcanic eruption spews orbs of magma which explode after a short delay, damaging nearby enemies. Cast speed increases the rate of magma orbs spewing.",
     "火山喷发涌出熔岩球，短暂延迟后爆炸，伤害附近敌人。施法速度提高熔岩球的喷涌频率。"),
    (291, '"name": "Arc",', '"name": "电弧",', "Arc", "电弧",
     292, '"description": "Sparks shock nearby enemies, dealing more damage to closer enemies.",',
     '"description": "电弧电击附近敌人，对更近的敌人造成更多伤害。",',
     "Sparks shock nearby enemies, dealing more damage to closer enemies.",
     "电弧电击附近敌人，对更近的敌人造成更多伤害。"),
    (301, '"name": "Battle Axe",', '"name": "战斧",', "Battle Axe", "战斧",
     302, '"description": "Throws a slow, heavy axe dealing extremely high damage.",',
     '"description": "投掷一把缓慢而沉重的战斧，造成极高的伤害。",',
     "Throws a slow, heavy axe dealing extremely high damage.",
     "投掷一把缓慢而沉重的战斧，造成极高的伤害。"),
    (311, '"name": "Blade Shield",', '"name": "利刃护盾",', "Blade Shield", "利刃护盾",
     312, '"description": "Summon an ethereal Blade to protect you, dealing Physical Damage to enemies hit by the blade. Blade Shield is unaffected by Cast Speed. Extra Projectiles reduce the cooldown instead.",',
     '"description": "召唤一柄以太利刃保护你，对命中的敌人造成物理伤害。利刃护盾不受施法速度影响，改为由额外投射物降低冷却时间。",',
     "Summon an ethereal Blade to protect you, dealing Physical Damage to enemies hit by the blade. Blade Shield is unaffected by Cast Speed. Extra Projectiles reduce the cooldown instead.",
     "召唤一柄以太利刃保护你，对命中的敌人造成物理伤害。利刃护盾不受施法速度影响，改为由额外投射物降低冷却时间。"),
    (321, '"name": "Shrapnel Bomb",', '"name": "破片炸弹",', "Shrapnel Bomb", "破片炸弹",
     322, '"description": "Throws a single explosive bomb which detonates after a delay, dealing massive damage. Shrapnel Bomb is not affected by extra projectiles.",',
     '"description": "投掷一枚爆炸炸弹，延迟后引爆，造成大量伤害。破片炸弹不受额外投射物影响。",',
     "Throws a single explosive bomb which detonates after a delay, dealing massive damage. Shrapnel Bomb is not affected by extra projectiles.",
     "投掷一枚爆炸炸弹，延迟后引爆，造成大量伤害。破片炸弹不受额外投射物影响。"),
    (331, '"name": "Cluster Bombs",', '"name": "集束炸弹",', "Cluster Bombs", "集束炸弹",
     332, '"description": "Throws a cluster of charged bombs which detonates, dealing damage in an area.",',
     '"description": "投掷一组充能炸弹，引爆后造成范围伤害。",',
     "Throws a cluster of charged bombs which detonates, dealing damage in an area.",
     "投掷一组充能炸弹，引爆后造成范围伤害。"),
    (341, '"name": "Shotgun",', '"name": "霰弹枪",', "Shotgun", "霰弹枪",
     342, '"description": "Short range, high damage skill.",',
     '"description": "短射程、高伤害的技能。",',
     "Short range, high damage skill.",
     "短射程、高伤害的技能。"),
    (351, '"name": "Minigun",', '"name": "迷你机枪",', "Minigun", "迷你机枪",
     352, '"description": "Rapid fire weapon.",',
     '"description": "高速连射的武器。",',
     "Rapid fire weapon.",
     "高速连射的武器。"),
    (361, '"name": "Poison Darts",', '"name": "剧毒飞镖",', "Poison Darts", "剧毒飞镖",
     362, '"description": "Poison an enemy for a duration.",',
     '"description": "使敌人中毒一段时间。",',
     "Poison an enemy for a duration.",
     "使敌人中毒一段时间。"),
    (371, '"name": "Shuriken",', '"name": "手里剑",', "Shuriken", "手里剑",
     372, '"description": "Inflict a high damage bleed on an enemy.",',
     '"description": "使敌人受到高伤害流血。",',
     "Inflict a high damage bleed on an enemy.",
     "使敌人受到高伤害流血。"),
    (381, '"name": "Shockwave",', '"name": "冲击波",', "Shockwave", "冲击波",
     382, '"description": "Slam the ground and release a powerful shock wave towards a nearby enemy, dealing damage in an area.",',
     '"description": "猛击地面，向附近敌人释放一道强力冲击波，造成范围伤害。",',
     "Slam the ground and release a powerful shock wave towards a nearby enemy, dealing damage in an area.",
     "猛击地面，向附近敌人释放一道强力冲击波，造成范围伤害。"),
    (391, '"name": "Blizzard",', '"name": "暴风雪",', "Blizzard", "暴风雪",
     392, '"description": "Chill and damage enemies in an area.",',
     '"description": "使区域内的敌人寒冷并造成伤害。",',
     "Chill and damage enemies in an area.",
     "使区域内的敌人寒冷并造成伤害。"),
    (401, '"name": "Plague Clouds",', '"name": "瘟疫之云",', "Plague Clouds", "瘟疫之云",
     402, '"description": "Leave a trail of toxic poison in your wake. All damage dealt by Plague Clouds is affected by Toxic Ailment Effect.",',
     '"description": "在你身后留下一道剧毒轨迹。瘟疫之云造成的所有伤害受毒素异常效果影响。",',
     "Leave a trail of toxic poison in your wake. All damage dealt by Plague Clouds is affected by Toxic Ailment Effect.",
     "在你身后留下一道剧毒轨迹。瘟疫之云造成的所有伤害受毒素异常效果影响。"),
    (411, '"name": "Debilitation Curse",', '"name": "衰弱诅咒",', "Debilitation Curse", "衰弱诅咒",
     412, '"description": "Curse enemies in an area with Debilitation, reducing their damage by 20%",',
     '"description": "诅咒区域内的敌人，使其衰弱，造成的伤害降低 20%",',
     "Curse enemies in an area with Debilitation, reducing their damage by 20%",
     "诅咒区域内的敌人，使其衰弱，造成的伤害降低 20%"),
    (420, '"name": "Hindering Curse",', '"name": "迟滞诅咒",', "Hindering Curse", "迟滞诅咒",
     421, '"description": "Curse enemies in an area with Hinder, reducing their movement speed by 30%.",',
     '"description": "诅咒区域内的敌人，使其迟滞，移动速度降低 30%。",',
     "Curse enemies in an area with Hinder, reducing their movement speed by 30%.",
     "诅咒区域内的敌人，使其迟滞，移动速度降低 30%。"),
    (429, '"name": "Brittle Curse",', '"name": "易碎诅咒",', "Brittle Curse", "易碎诅咒",
     430, '"description": "Curse enemies in an area with Brittle, increasing their damage taken by 20%.",',
     '"description": "诅咒区域内的敌人，使其易碎，受到的伤害提高 20%。",',
     "Curse enemies in an area with Brittle, increasing their damage taken by 20%.",
     "诅咒区域内的敌人，使其易碎，受到的伤害提高 20%。"),
    (438, '"name": "Scorch Curse",', '"name": "灼烧诅咒",', "Scorch Curse", "灼烧诅咒",
     439, '"description": "Curse enemies in an area with Scorch, lowering their Fire Resistance by 10%.",',
     '"description": "诅咒区域内的敌人，使其灼烧，火焰抗性降低 10%。",',
     "Curse enemies in an area with Scorch, lowering their Fire Resistance by 10%.",
     "诅咒区域内的敌人，使其灼烧，火焰抗性降低 10%。"),
    (447, '"name": "Protracting Curse",', '"name": "延长诅咒",', "Protracting Curse", "延长诅咒",
     448, '"description": "Curse enemies in an area with Protraction, increasing duration of effects on them by 30%.",',
     '"description": "诅咒区域内的敌人，使其效果持续时间延长 30%。",',
     "Curse enemies in an area with Protraction, increasing duration of effects on them by 30%.",
     "诅咒区域内的敌人，使其效果持续时间延长 30%。"),
    (456, '"name": "Bane Curse",', '"name": "灾厄诅咒",', "Bane Curse", "灾厄诅咒",
     457, '"description": "Curse enemies in an area with Bane, lowering their Toxic Resistance by 10%.",',
     '"description": "诅咒区域内的敌人，使其中毒抗性降低 10%。",',
     "Curse enemies in an area with Bane, lowering their Toxic Resistance by 10%.",
     "诅咒区域内的敌人，使其中毒抗性降低 10%。"),
    (465, '"name": "Polarize Curse",', '"name": "极化诅咒",', "Polarize Curse", "极化诅咒",
     466, '"description": "Curse enemies in an area with Polarize, lowering their Lightning Resistance by 10%.",',
     '"description": "诅咒区域内的敌人，使其闪电抗性降低 10%。",',
     "Curse enemies in an area with Polarize, lowering their Lightning Resistance by 10%.",
     "诅咒区域内的敌人，使其闪电抗性降低 10%。"),
    (474, '"name": "Hypothermia Curse",', '"name": "失温诅咒",', "Hypothermia Curse", "失温诅咒",
     475, '"description": "Curse enemies in an area with Hyptothermia, lowering their Cold Resistance by 10%.",',
     '"description": "诅咒区域内的敌人，使其失温，寒冷抗性降低 10%。",',
     "Curse enemies in an area with Hyptothermia, lowering their Cold Resistance by 10%.",
     "诅咒区域内的敌人，使其失温，寒冷抗性降低 10%。"),
    (483, '"name": "Arrow Draw",', '"name": "开弓射击",', "Arrow Draw", "开弓射击",
     484, '"description": "Fires an arrow dealing high physical damage.",',
     '"description": "射出一支造成高额物理伤害的箭矢。",',
     "Fires an arrow dealing high physical damage.",
     "射出一支造成高额物理伤害的箭矢。"),
    (493, '"name": "Sharknado Shot",', '"name": "鲨卷风射击",', "Sharknado Shot", "鲨卷风射击",
     494, '"description": "Fires a mother shark at a nearby enemy, releasing a burst of dangerous baby sharks at nearby enemies.",',
     '"description": "向附近敌人发射一条母鲨，向附近敌人释放一群危险的幼鲨。",',
     "Fires a mother shark at a nearby enemy, releasing a burst of dangerous baby sharks at nearby enemies.",
     "向附近敌人发射一条母鲨，向附近敌人释放一群危险的幼鲨。"),
    (505, '"name": "Prismatic Slash",', '"name": "棱光斩击",', "Prismatic Slash", "棱光斩击",
     506, '"description": "Slash in an arc towards a nearby enemy, dealing damage in a cone. All Damage is applied as Fire, Lightning, or Cold at random. Every 3rd attack always inflicts a Critical Strike.",',
     '"description": "向附近敌人挥出一道弧形斩击，造成锥形伤害。所有伤害随机以火焰、闪电或寒冷方式结算。每第 3 次攻击必定造成暴击。",',
     "Slash in an arc towards a nearby enemy, dealing damage in a cone. All Damage is applied as Fire, Lightning, or Cold at random. Every 3rd attack always inflicts a Critical Strike.",
     "向附近敌人挥出一道弧形斩击，造成锥形伤害。所有伤害随机以火焰、闪电或寒冷方式结算。每第 3 次攻击必定造成暴击。"),
    (515, '"name": "Energized Axe",', '"name": "充能战斧",', "Energized Axe", "充能战斧",
     516, '"description": "Swing a Lightning Infused Axe in an arc towards nearby enemies.",',
     '"description": "向附近敌人挥出弧形一击，战斧灌注闪电之力。",',
     "Swing a Lightning Infused Axe in an arc towards nearby enemies.",
     "向附近敌人挥出弧形一击，战斧灌注闪电之力。"),
    (525, '"name": "Lacerating Slash",', '"name": "撕裂斩击",', "Lacerating Slash", "撕裂斩击",
     526, '"description": "Swing a serrated blade at nearby enemies, dealing damage with a chance to inflict Bleeds.",',
     '"description": "向附近敌人挥动锯齿利刃造成伤害，有几率使其流血。",',
     "Swing a serrated blade at nearby enemies, dealing damage with a chance to inflict Bleeds.",
     "向附近敌人挥动锯齿利刃造成伤害，有几率使其流血。"),
    (537, '"name": "Rush Aura",', '"name": "疾行光环",', "Rush Aura", "疾行光环",
     538, '"description": "You and nearby allies move faster.",',
     '"description": "你和附近队友移动速度提高。",',
     "You and nearby allies move faster.",
     "你和附近队友移动速度提高。"),
    (546, '"name": "Regeneration Aura",', '"name": "再生光环",', "Regeneration Aura", "再生光环",
     547, '"description": "You and nearby allies regenerate life.",',
     '"description": "你和附近队友回复生命。",',
     "You and nearby allies regenerate life.",
     "你和附近队友回复生命。"),
    (555, '"name": "Resilience Aura",', '"name": "坚韧光环",', "Resilience Aura", "坚韧光环",
     556, '"description": "You and nearby allies have a reduced chance to be inflicted by ailments.",',
     '"description": "你和附近队友受到异常状态影响的几率降低。",',
     "You and nearby allies have a reduced chance to be inflicted by ailments.",
     "你和附近队友受到异常状态影响的几率降低。"),
    (564, '"name": "Sturdiness Aura",', '"name": "健壮光环",', "Sturdiness Aura", "健壮光环",
     565, '"description": "You and nearby allies gain Armor.",',
     '"description": "你和附近队友获得护甲。",',
     "You and nearby allies gain Armor.",
     "你和附近队友获得护甲。"),
    (573, '"name": "Elusiveness Aura",', '"name": "闪避光环",', "Elusiveness Aura", "闪避光环",
     574, '"description": "You and nearby allies gain Evasion.",',
     '"description": "你和附近队友获得闪避。",',
     "You and nearby allies gain Evasion.",
     "你和附近队友获得闪避。"),
    (582, '"name": "Honing Aura",', '"name": "磨砺光环",', "Honing Aura", "磨砺光环",
     583, '"description": "You and nearby allies gain Critical Strike Chance and Cast Speed.",',
     '"description": "你和附近队友获得暴击几率与施法速度。",',
     "You and nearby allies gain Critical Strike Chance and Cast Speed.",
     "你和附近队友获得暴击几率与施法速度。"),
    (591, '"name": "Amplification Aura",', '"name": "增幅光环",', "Amplification Aura", "增幅光环",
     592, '"description": "You and nearby allies gain More Damage.",',
     '"description": "你和附近队友获得更多伤害。",',
     "You and nearby allies gain More Damage.",
     "你和附近队友获得更多伤害。"),
    (600, '"name": "Metallic Aura",', '"name": "金属光环",', "Metallic Aura", "金属光环",
     601, '"description": "You and nearby allies gain bonuses with Physical Damage.",',
     '"description": "你和附近队友获得物理伤害加成。",',
     "You and nearby allies gain bonuses with Physical Damage.",
     "你和附近队友获得物理伤害加成。"),
    (609, '"name": "Static Aura",', '"name": "静电光环",', "Static Aura", "静电光环",
     610, '"description": "You and nearby allies gain bonuses with Lightning Damage.",',
     '"description": "你和附近队友获得闪电伤害加成。",',
     "You and nearby allies gain bonuses with Lightning Damage.",
     "你和附近队友获得闪电伤害加成。"),
    (618, '"name": "Frigid Aura",', '"name": "严寒光环",', "Frigid Aura", "严寒光环",
     619, '"description": "You and nearby allies gain bonuses with Cold Damage",',
     '"description": "你和附近队友获得寒冷伤害加成",',
     "You and nearby allies gain bonuses with Cold Damage",
     "你和附近队友获得寒冷伤害加成"),
    (627, '"name": "Flame Aura",', '"name": "烈焰光环",', "Flame Aura", "烈焰光环",
     628, '"description": "You and nearby allies gain bonuses with Fire Damage.",',
     '"description": "你和附近队友获得火焰伤害加成。",',
     "You and nearby allies gain bonuses with Fire Damage.",
     "你和附近队友获得火焰伤害加成。"),
    (636, '"name": "Vile Aura",', '"name": "污秽光环",', "Vile Aura", "污秽光环",
     637, '"description": "You and nearby allies gain bonuses with Toxic Damage.",',
     '"description": "你和附近队友获得毒素伤害加成。",',
     "You and nearby allies gain bonuses with Toxic Damage.",
     "你和附近队友获得毒素伤害加成。"),
    (645, '"name": "Contagion Aura",', '"name": "传染光环",', "Contagion Aura", "传染光环",
     646, '"description": "You and nearby allies gain bonuses with Damage over Time.",',
     '"description": "你和附近队友获得持续伤害加成。",',
     "You and nearby allies gain bonuses with Damage over Time.",
     "你和附近队友获得持续伤害加成。"),
    (656, '"name": "Dread Aura",', '"name": "恐惧光环",', "Dread Aura", "恐惧光环",
     657, '"description": "Nearby Enemies are afflicted by Dread. Dread causes Enemies to take 25% More Damage per unique Non-Enhanced Elemental Ailment on them.",',
     '"description": "附近敌人受到恐惧影响。敌人身上的每种未强化的元素异常状态，都会使其受到 25% 更多伤害。",',
     "Nearby Enemies are afflicted by Dread. Dread causes Enemies to take 25% More Damage per unique Non-Enhanced Elemental Ailment on them.",
     "附近敌人受到恐惧影响。敌人身上的每种未强化的元素异常状态，都会使其受到 25% 更多伤害。"),
    (663, '"name": "Blood Burst",', '"name": "鲜血爆发",', "Blood Burst", "鲜血爆发",
     664, '"description": "Release an explosion of Boiling Blood, dealing base 250% of your Maximum Life as Fire Damage to nearby Enemies. Blood Burst always inflicts Burn.",',
     '"description": "释放沸腾鲜血的爆炸，以你最大生命值 250% 的基础量向附近敌人造成火焰伤害。鲜血爆发必定造成灼烧。",',
     "Release an explosion of Boiling Blood, dealing base 250% of your Maximum Life as Fire Damage to nearby Enemies. Blood Burst always inflicts Burn.",
     "释放沸腾鲜血的爆炸，以你最大生命值 250% 的基础量向附近敌人造成火焰伤害。鲜血爆发必定造成灼烧。"),
    (671, '"name": "Vile Domain",', '"name": "污秽领域",', "Vile Domain", "污秽领域",
     672, '"description": "Nearby Enemies count as Poisoned. Nearby Enemies take 20% More Damage.",',
     '"description": "附近敌人被视为中毒状态。附近敌人受到 20% 更多伤害。",',
     "Nearby Enemies count as Poisoned. Nearby Enemies take 20% More Damage.",
     "附近敌人被视为中毒状态。附近敌人受到 20% 更多伤害。"),
    (678, '"name": "Energetic Flesh",', '"name": "能量之躯",', "Energetic Flesh", "能量之躯",
     679, '"description": "Nearby Jolted Enemies take 300% of your Maximum Life as Lightning Damage per Second. Deals More Damage equal to your Lightning Ailment Effect.",',
     '"description": "附近受电击影响的敌人每秒受到你最大生命值 300% 的闪电伤害。造成等同于你闪电异常效果的更多伤害。",',
     "Nearby Jolted Enemies take 300% of your Maximum Life as Lightning Damage per Second. Deals More Damage equal to your Lightning Ailment Effect.",
     "附近受电击影响的敌人每秒受到你最大生命值 300% 的闪电伤害。造成等同于你闪电异常效果的更多伤害。"),
    (686, '"name": "Bonded Electrons",', '"name": "电子结合",', "Bonded Electrons", "电子结合",
     687, '"description": "Nearby Enemies have Lightning Resistance equal to yours.",',
     '"description": "附近敌人的闪电抗性等同于你的闪电抗性。",',
     "Nearby Enemies have Lightning Resistance equal to yours.",
     "附近敌人的闪电抗性等同于你的闪电抗性。"),
]

# SkillSupports.gd entries
SUPPORTS = [
    (42, '"name": "Extra Munitions",', '"name": "额外弹药",', "Extra Munitions", "额外弹药",
     43, '"description": "Skill fires extra projectiles, each dealing less damage.",',
     '"description": "技能发射额外投射物，每个造成更少伤害。",',
     "Skill fires extra projectiles, each dealing less damage.",
     "技能发射额外投射物，每个造成更少伤害。"),
    (60, '"name": "Sniper",', '"name": "狙击手",', "Sniper", "狙击手",
     61, '"description": "Projectiles fire with no spread.",',
     '"description": "投射物无散射发射。",',
     "Projectiles fire with no spread.",
     "投射物无散射发射。"),
    (69, '"name": "Collateral Damage",', '"name": "附带伤害",', "Collateral Damage", "附带伤害",
     70, '"description": "Projectiles deal damage to nearby enemies on hit.",',
     '"description": "投射物命中时对附近敌人造成伤害。",',
     "Projectiles deal damage to nearby enemies on hit.",
     "投射物命中时对附近敌人造成伤害。"),
    (78, '"name": "Puncturing Shots",', '"name": "贯穿射击",', "Puncturing Shots", "贯穿射击",
     79, '"description": "Projectiles pierce enemies.",',
     '"description": "投射物穿透敌人。",',
     "Projectiles pierce enemies.",
     "投射物穿透敌人。"),
    (91, '"name": "Ricocheting Shots",', '"name": "弹射射击",', "Ricocheting Shots", "弹射射击",
     92, '"description": "Projectiles that can chain to nearby enemies.",',
     '"description": "投射物可连锁至附近敌人。",',
     "Projectiles that can chain to nearby enemies.",
     "投射物可连锁至附近敌人。"),
    (109, '"name": "Quicker Projectiles",', '"name": "快速投射物",', "Quicker Projectiles", "快速投射物",
     110, '"description": "Projectiles travel with increased speed.",',
     '"description": "投射物以更高的速度飞行。",',
     "Projectiles travel with increased speed.",
     "投射物以更高的速度飞行。"),
    (122, '"name": "Focus",', '"name": "专注",', "Focus", "专注",
     123, '"description": "Skill never deals Critical Strikes, but deals More Damage.",',
     '"description": "技能永远不会造成暴击，但造成更多伤害。",',
     "Skill never deals Critical Strikes, but deals More Damage.",
     "技能永远不会造成暴击，但造成更多伤害。"),
    (140, '"name": "Proliferation",', '"name": "扩散",', "Proliferation", "扩散",
     141, '"description": "Elemental Ailments inflicted by this Skill also apply to 10 random nearby enemies.",',
     '"description": "此技能造成的元素异常状态同样作用于附近 10 名随机敌人。",',
     "Elemental Ailments inflicted by this Skill also apply to 10 random nearby enemies.",
     "此技能造成的元素异常状态同样作用于附近 10 名随机敌人。"),
    (148, '"name": "Capacitor Discharging",', '"name": "电容器放电",', "Capacitor Discharging", "电容器放电",
     149, '"description": "Inflict Lightning to nearby enemies when hitting Jolted enemies.",',
     '"description": "命中受电击影响的敌人时，对附近敌人造成闪电伤害。",',
     "Inflict Lightning to nearby enemies when hitting Jolted enemies.",
     "命中受电击影响的敌人时，对附近敌人造成闪电伤害。"),
    (162, '"name": "Hamstring",', '"name": "断筋",', "Hamstring", "断筋",
     163, '"description": "Deal more Physical Damage with Melee Attacks, and inflicts Hamstrung for 4 seconds on hit.",',
     '"description": "近战攻击造成更多物理伤害，命中时使敌人断筋 4 秒。",',
     "Deal more Physical Damage with Melee Attacks, and inflicts Hamstrung for 4 seconds on hit.",
     "近战攻击造成更多物理伤害，命中时使敌人断筋 4 秒。"),
    (176, '"name": "Critical Honing",', '"name": "暴击磨砺",', "Critical Honing", "暴击磨砺",
     177, '"description": "Skill has a higher chance to deal critical strikes.",',
     '"description": "技能造成暴击的几率提高。",',
     "Skill has a higher chance to deal critical strikes.",
     "技能造成暴击的几率提高。"),
    (194, '"name": "Critical Mass",', '"name": "暴击质量",', "Critical Mass", "暴击质量",
     195, '"description": "Skill deals more damage with critical strikes.",',
     '"description": "技能造成暴击时造成更多伤害。",',
     "Skill deals more damage with critical strikes.",
     "技能造成暴击时造成更多伤害。"),
    (207, '"name": "Sacrifice",', '"name": "牺牲",', "Sacrifice", "牺牲",
     208, '"description": "Sacrifices Life to gain Added Physical Damage.",',
     '"description": "牺牲生命以获得额外物理伤害。",',
     "Sacrifices Life to gain Added Physical Damage.",
     "牺牲生命以获得额外物理伤害。"),
    (215, '"name": "Bloody",', '"name": "血腥",', "Bloody", "血腥",
     216, '"description": "Skill deals more damage with Bleeds and Ruptures, and has a higher chance to inflict Bleeds.",',
     '"description": "技能的流血与撕裂造成更多伤害，且有更高几率造成流血。",',
     "Skill deals more damage with Bleeds and Ruptures, and has a higher chance to inflict Bleeds.",
     "技能的流血与撕裂造成更多伤害，且有更高几率造成流血。"),
    (233, '"name": "Ignition",', '"name": "点燃",', "Ignition", "点燃",
     234, '"description": "Skill deals more damage with Burns, and has a higher chance to inflict Burn.",',
     '"description": "技能的灼烧造成更多伤害，且有更高几率造成灼烧。",',
     "Skill deals more damage with Burns, and has a higher chance to inflict Burn.",
     "技能的灼烧造成更多伤害，且有更高几率造成灼烧。"),
    (251, '"name": "Chilling",', '"name": "冰寒",', "Chilling", "冰寒",
     252, '"description": "Chills and Freezes inflicted have more effect.",',
     '"description": "造成的寒冷与冻结效果提高。",',
     "Chills and Freezes inflicted have more effect.",
     "造成的寒冷与冻结效果提高。"),
    (269, '"name": "Charged",', '"name": "充能",', "Charged", "充能",
     270, '"description": "Jolts and Electrocutions inflicted have more effect.",',
     '"description": "造成的电击与感电效果提高。",',
     "Jolts and Electrocutions inflicted have more effect.",
     "造成的电击与感电效果提高。"),
    (287, '"name": "Poison",', '"name": "毒素",', "Poison", "毒素",
     288, '"description": "Skill deals more damage with Poisons and Infections, and has a higher chance to inflict Poisons.",',
     '"description": "技能的中毒与感染造成更多伤害，且有更高几率造成中毒。",',
     "Skill deals more damage with Poisons and Infections, and has a higher chance to inflict Poisons.",
     "技能的中毒与感染造成更多伤害，且有更高几率造成中毒。"),
    (305, '"name": "Wizardry",', '"name": "巫术",', "Wizardry", "巫术",
     306, '"description": "Skill is cast at a faster rate",',
     '"description": "技能以更快的速度施放",',
     "Skill is cast at a faster rate",
     "技能以更快的速度施放"),
    (318, '"name": "Cold Attuned",', '"name": "寒冰亲和",', "Cold Attuned", "寒冰亲和",
     319, '"description": "Skill converts some Physical damage into Cold Damage",',
     '"description": "技能将部分物理伤害转化为寒冷伤害",',
     "Skill converts some Physical damage into Cold Damage",
     "技能将部分物理伤害转化为寒冷伤害"),
    (331, '"name": "Shock Attuned",', '"name": "闪电亲和",', "Shock Attuned", "闪电亲和",
     332, '"description": "Skill converts some Physical damage into Lightning Damage",',
     '"description": "技能将部分物理伤害转化为闪电伤害",',
     "Skill converts some Physical damage into Lightning Damage",
     "技能将部分物理伤害转化为闪电伤害"),
    (344, '"name": "Fire Attuned",', '"name": "火焰亲和",', "Fire Attuned", "火焰亲和",
     345, '"description": "Skill converts some Physical damage into Fire Damage",',
     '"description": "技能将部分物理伤害转化为火焰伤害",',
     "Skill converts some Physical damage into Fire Damage",
     "技能将部分物理伤害转化为火焰伤害"),
    (357, '"name": "Expansive",', '"name": "广域",', "Expansive", "广域",
     358, '"description": "Skill affects a larger area, and will deal more area damage",',
     '"description": "技能影响更大的区域，并造成更多范围伤害",',
     "Skill affects a larger area, and will deal more area damage",
     "技能影响更大的区域，并造成更多范围伤害"),
    (376, '"name": "Physical Damage",', '"name": "物理伤害",', "Physical Damage", "物理伤害",
     377, '"description": "Skill deals more Physical Damage",',
     '"description": "技能造成更多物理伤害",',
     "Skill deals more Physical Damage",
     "技能造成更多物理伤害"),
    (389, '"name": "Lightning Damage",', '"name": "闪电伤害",', "Lightning Damage", "闪电伤害",
     390, '"description": "Skill deals more Lightning Damage",',
     '"description": "技能造成更多闪电伤害",',
     "Skill deals more Lightning Damage",
     "技能造成更多闪电伤害"),
    (402, '"name": "Cold Damage",', '"name": "寒冷伤害",', "Cold Damage", "寒冷伤害",
     403, '"description": "Skill deals more Cold Damage",',
     '"description": "技能造成更多寒冷伤害",',
     "Skill deals more Cold Damage",
     "技能造成更多寒冷伤害"),
    (415, '"name": "Fire Damage",', '"name": "火焰伤害",', "Fire Damage", "火焰伤害",
     416, '"description": "Skill deals more Fire Damage",',
     '"description": "技能造成更多火焰伤害",',
     "Skill deals more Fire Damage",
     "技能造成更多火焰伤害"),
    (428, '"name": "Toxic Damage",', '"name": "毒素伤害",', "Toxic Damage", "毒素伤害",
     429, '"description": "Skill deals more Toxic Damage",',
     '"description": "技能造成更多毒素伤害",',
     "Skill deals more Toxic Damage",
     "技能造成更多毒素伤害"),
    (441, '"name": "Physical Penetration",', '"name": "物理穿透",', "Physical Penetration", "物理穿透",
     442, '"description": "Physical Damage with skill penetrates Physical Resistance on enemies.",',
     '"description": "技能的物理伤害穿透敌人的物理抗性。",',
     "Physical Damage with skill penetrates Physical Resistance on enemies.",
     "技能的物理伤害穿透敌人的物理抗性。"),
    (454, '"name": "Lightning Penetration",', '"name": "闪电穿透",', "Lightning Penetration", "闪电穿透",
     455, '"description": "Lightning Damage with skill penetrates Lightning Resistance on enemies.",',
     '"description": "技能的闪电伤害穿透敌人的闪电抗性。",',
     "Lightning Damage with skill penetrates Lightning Resistance on enemies.",
     "技能的闪电伤害穿透敌人的闪电抗性。"),
    (467, '"name": "Cold Penetration",', '"name": "寒冷穿透",', "Cold Penetration", "寒冷穿透",
     468, '"description": "Cold Damage with skill penetrates Cold Resistance on enemies.",',
     '"description": "技能的寒冷伤害穿透敌人的寒冷抗性。",',
     "Cold Damage with skill penetrates Cold Resistance on enemies.",
     "技能的寒冷伤害穿透敌人的寒冷抗性。"),
    (480, '"name": "Fire Penetration",', '"name": "火焰穿透",', "Fire Penetration", "火焰穿透",
     481, '"description": "Fire Damage with skill penetrates Fire Resistance on enemies.",',
     '"description": "技能的火焰伤害穿透敌人的火焰抗性。",',
     "Fire Damage with skill penetrates Fire Resistance on enemies.",
     "技能的火焰伤害穿透敌人的火焰抗性。"),
    (493, '"name": "Toxic Penetration",', '"name": "毒素穿透",', "Toxic Penetration", "毒素穿透",
     494, '"description": "Toxic Damage with skill penetrates Toxic Resistance on enemies.",',
     '"description": "技能的毒素伤害穿透敌人的毒素抗性。",',
     "Toxic Damage with skill penetrates Toxic Resistance on enemies.",
     "技能的毒素伤害穿透敌人的毒素抗性。"),
    (506, '"name": "Frigid Static",', '"name": "寒冰静电",', "Frigid Static", "寒冰静电",
     507, '"description": "Convert a portion of Lightning Damage into Cold Damage.",',
     '"description": "将部分闪电伤害转化为寒冷伤害。",',
     "Convert a portion of Lightning Damage into Cold Damage.",
     "将部分闪电伤害转化为寒冷伤害。"),
    (519, '"name": "Extra Fire",', '"name": "额外火焰",', "Extra Fire", "额外火焰",
     520, '"description": "Extra Fire Damage from Physical",',
     '"description": "由物理伤害获得额外火焰伤害",',
     "Extra Fire Damage from Physical",
     "由物理伤害获得额外火焰伤害"),
    (532, '"name": "Burning Static",', '"name": "燃烧静电",', "Burning Static", "燃烧静电",
     533, '"description": "Convert a portion of Lightning Damage into Fire Damage.",',
     '"description": "将部分闪电伤害转化为火焰伤害。",',
     "Convert a portion of Lightning Damage into Fire Damage.",
     "将部分闪电伤害转化为火焰伤害。"),
    (545, '"name": "Vile Static",', '"name": "污秽静电",', "Vile Static", "污秽静电",
     546, '"description": "Convert a portion of Lightning Damage into Toxic Damage",',
     '"description": "将部分闪电伤害转化为毒素伤害",',
     "Convert a portion of Lightning Damage into Toxic Damage",
     "将部分闪电伤害转化为毒素伤害"),
    (558, '"name": "Ailment Duration",', '"name": "异常持续时间",', "Ailment Duration", "异常持续时间",
     559, '"description": "Ailments inflicted by this skill last longer.",',
     '"description": "此技能造成的异常状态持续时间更长。",',
     "Ailments inflicted by this skill last longer.",
     "此技能造成的异常状态持续时间更长。"),
    (571, '"name": "Enhanced Ailments",', '"name": "强化异常",', "Enhanced Ailments", "强化异常",
     572, '"description": "Ailments inflicted by this skill have a chance to inflicted the enhanced version as well.",',
     '"description": "此技能造成的异常状态有几率同时造成强化版本。",',
     "Ailments inflicted by this skill have a chance to inflicted the enhanced version as well.",
     "此技能造成的异常状态有几率同时造成强化版本。"),
    (584, '"name": "Increased Duration",', '"name": "持续时间提高",', "Increased Duration", "持续时间提高",
     585, '"description": "Skill lasts longer.",',
     '"description": "技能持续时间更长。",',
     "Skill lasts longer.",
     "技能持续时间更长。"),
    (597, '"name": "Potent Suppression",', '"name": "强力压制",', "Potent Suppression", "强力压制",
     598, '"description": "Damage over Time inflicted by this skill deal more damage.",',
     '"description": "此技能造成的持续伤害造成更多伤害。",',
     "Damage over Time inflicted by this skill deal more damage.",
     "此技能造成的持续伤害造成更多伤害。"),
    (610, '"name": "Vulnerability",', '"name": "易伤",', "Vulnerability", "易伤",
     611, '"description": "Skill has a chance to inflict Vulnerable on hit, with increased effect.",',
     '"description": "技能命中时有机会造成易伤，且效果提高。",',
     "Skill has a chance to inflict Vulnerable on hit, with increased effect.",
     "技能命中时有机会造成易伤，且效果提高。"),
    (628, '"name": "Weakness",', '"name": "虚弱",', "Weakness", "虚弱",
     629, '"description": "Skill has a chance to inflict Exposure on hit, with increased effect.",',
     '"description": "技能命中时有机会造成暴露，且效果提高。",',
     "Skill has a chance to inflict Exposure on hit, with increased effect.",
     "技能命中时有机会造成暴露，且效果提高。"),
    (648, '"name": "Doomed",', '"name": "宿命",', "Doomed", "宿命",
     649, '"description": "Skill has more effect of curses.",',
     '"description": "技能的诅咒效果提高。",',
     "Skill has more effect of curses.",
     "技能的诅咒效果提高。"),
    (661, '"name": "Large Curses",', '"name": "巨型诅咒",', "Large Curses", "巨型诅咒",
     662, '"description": "Skill has a larger area of effect of curses",',
     '"description": "技能的诅咒影响范围更大",',
     "Skill has a larger area of effect of curses",
     "技能的诅咒影响范围更大"),
    (675, '"name": "Lacerating",', '"name": "撕裂",', "Lacerating", "撕裂",
     676, '"description": "Bleeds and Ruptures inflicted by this skill have increased effect.",',
     '"description": "此技能造成的流血与撕裂效果提高。",',
     "Bleeds and Ruptures inflicted by this skill have increased effect.",
     "此技能造成的流血与撕裂效果提高。"),
    (688, '"name": "Scorched",', '"name": "焦灼",', "Scorched", "焦灼",
     689, '"description": "Burns and Chars inflicted by this skill have increased effect.",',
     '"description": "此技能造成的灼烧与焦黑效果提高。",',
     "Burns and Chars inflicted by this skill have increased effect.",
     "此技能造成的灼烧与焦黑效果提高。"),
    (701, '"name": "Frigid",', '"name": "严寒",', "Frigid", "严寒",
     702, '"description": "Chills and Freezes inflicted by this skill have increased effect.",',
     '"description": "此技能造成的寒冷与冻结效果提高。",',
     "Chills and Freezes inflicted by this skill have increased effect.",
     "此技能造成的寒冷与冻结效果提高。"),
    (714, '"name": "Stunner",', '"name": "眩晕者",', "Stunner", "眩晕者",
     715, '"description": "Jolts and Electrocutions inflicted by this skill have increased effect.",',
     '"description": "此技能造成的电击与感电效果提高。",',
     "Jolts and Electrocutions inflicted by this skill have increased effect.",
     "此技能造成的电击与感电效果提高。"),
    (727, '"name": "Venom",', '"name": "剧毒",', "Venom", "剧毒",
     728, '"description": "Poisons and Infections inflicted by this skill have increased effect.",',
     '"description": "此技能造成的中毒与感染效果提高。",',
     "Poisons and Infections inflicted by this skill have increased effect.",
     "此技能造成的中毒与感染效果提高。"),
    (740, '"name": "Weightlifting",', '"name": "举重训练",', "Weightlifting", "举重训练",
     741, '"description": "Strength provides Added Physical Damage.",',
     '"description": "力量提供额外物理伤害。",',
     "Strength provides Added Physical Damage.",
     "力量提供额外物理伤害。"),
    (753, '"name": "Igni Study",', '"name": "火焰研习",', "Igni Study", "火焰研习",
     754, '"description": "Constitution provides Added Fire Damage.",',
     '"description": "体质提供额外火焰伤害。",',
     "Constitution provides Added Fire Damage.",
     "体质提供额外火焰伤害。"),
    (766, '"name": "Cryo Study",', '"name": "寒冰研习",', "Cryo Study", "寒冰研习",
     767, '"description": "Widsom provides Added Cold Damage.",',
     '"description": "智慧提供额外寒冷伤害。",',
     "Widsom provides Added Cold Damage.",
     "智慧提供额外寒冷伤害。"),
    (779, '"name": "Conductive Movement",', '"name": "导电移动",', "Conductive Movement", "导电移动",
     780, '"description": "Agility provides Added Lightning Damage.",',
     '"description": "敏捷提供额外闪电伤害。",',
     "Agility provides Added Lightning Damage.",
     "敏捷提供额外闪电伤害。"),
    (792, '"name": "Finessed Toxins",', '"name": "精巧毒素",', "Finessed Toxins", "精巧毒素",
     793, '"description": "Finesse provides Added Toxic Damage.",',
     '"description": "灵巧提供额外毒素伤害。",',
     "Finesse provides Added Toxic Damage.",
     "灵巧提供额外毒素伤害。"),
    (805, '"name": "Infection",', '"name": "感染",', "Infection", "感染",
     806, '"description": "Infections inflicted by this skill spread to more nearby enemies.",',
     '"description": "此技能造成的感染会传播至更多附近敌人。",',
     "Infections inflicted by this skill spread to more nearby enemies.",
     "此技能造成的感染会传播至更多附近敌人。"),
    (818, '"name": "Cast on Crit",', '"name": "暴击时施放",', "Cast on Crit", "暴击时施放",
     819, '"description": "Skill is cast when another skill inflicts a critical strike. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",',
     '"description": "当其他技能造成暴击时施放此技能。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。",',
     "Skill is cast when another skill inflicts a critical strike. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",
     "当其他技能造成暴击时施放此技能。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。"),
    (833, '"name": "Cast on Kill",', '"name": "击杀时施放",', "Cast on Kill", "击杀时施放",
     834, '"description": "Skill has a 30% chance to cast when another skill inflicts a killing blow. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",',
     '"description": "当其他技能造成击杀时，此技能有 30% 几率施放。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。",',
     "Skill has a 30% chance to cast when another skill inflicts a killing blow. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",
     "当其他技能造成击杀时，此技能有 30% 几率施放。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。"),
    (848, '"name": "Volatility",', '"name": "易变",', "Volatility", "易变",
     849, '"description": "Skill is cast when hitting an enemy with any non-triggered skill. Skill consumes a random number of Boons to deal 20% more damage for each consumed Boon. Must have at least one active boon to cast. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",',
     '"description": "用任何非触发技能命中敌人时施放此技能。此技能消耗随机数量的恩惠，每消耗一个恩惠造成 20% 更多伤害。施放时至少需要一个激活的恩惠。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。",',
     "Skill is cast when hitting an enemy with any non-triggered skill. Skill consumes a random number of Boons to deal 20% more damage for each consumed Boon. Must have at least one active boon to cast. Skill does not auto cast, and cannot trigger other skills. All Triggered skills have a 100ms cooldown.",
     "用任何非触发技能命中敌人时施放此技能。此技能消耗随机数量的恩惠，每消耗一个恩惠造成 20% 更多伤害。施放时至少需要一个激活的恩惠。此技能不会自动施放，也无法触发其他技能。所有被触发的技能共享 100ms 冷却。"),
    (863, '"name": "Precision Boon on Critical Strike",', '"name": "暴击获得精准恩惠",', "Precision Boon on Critical Strike", "暴击获得精准恩惠",
     864, '"description": "Skill has a chance to grant a Precision Boon on crit.",',
     '"description": "技能暴击时有机会获得一个精准恩惠。",',
     "Skill has a chance to grant a Precision Boon on crit.",
     "技能暴击时有机会获得一个精准恩惠。"),
]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build_patches(entries, src_path, content, lines):
    patches = []
    preimage = sha256_file(src_path).upper()
    for (lname, oname, nname, sname, tname, ldesc, odesc, ndesc, sdesc, tdesc) in entries:
        for line_no, old, new, src, tr in (
            (lname, oname, nname, sname, tname),
            (ldesc, odesc, ndesc, sdesc, tdesc),
        ):
            if line_no - 1 >= len(lines):
                raise SystemExit(f"line out of range: {src_path}:{line_no}")
            actual = lines[line_no - 1].strip()
            if old != actual:
                raise SystemExit(f"line mismatch {src_path}:{line_no}\n expected: {old}\n actual:   {actual}")
            count = content.count(old)
            if count != 1:
                raise SystemExit(f"occurrence {count} for {old} at {src_path}:{line_no} (must be 1)")
            col = actual.find('"') + 1
            rel = src_path.relative_to(ROOT / "04_recovered").as_posix()
            patches.append({
                "path": rel,
                "field": "text",
                "classification": "TEXT_PATCH",
                "unit_id": f"{rel}:{line_no}:{col}",
                "old_text": old,
                "new_text": new,
                "preimage_sha256": preimage,
                "expected_occurrences": 1,
                "source_text": src,
                "translation": tr,
                "placeholders": [],
                "format_tokens": [],
                "tests": [
                    "unit_id_exact_match",
                    "placeholder_conservation",
                    "token_conservation",
                    "resource_contract",
                    "declared_delta",
                    "compiled_script_load",
                ],
            })
    return patches


def main():
    skills_path = ROOT / "04_recovered/Globals/Skills.gd"
    supports_path = ROOT / "04_recovered/Globals/SkillSupports.gd"
    skills_content = skills_path.read_text(encoding="utf-8")
    supports_content = supports_path.read_text(encoding="utf-8")

    patches = []
    patches += build_patches(SKILLS, skills_path, skills_content, skills_content.splitlines())
    patches += build_patches(SUPPORTS, supports_path, supports_content, supports_content.splitlines())

    manifest = {
        "id": "c5-l10-skills-tree-zhcn",
        "version": "0.1.0",
        "patch_type": "TEXT_PATCH",
        "target_original_sha256": "C7B5D5A529CD776609F72730662F1F6A8049FE5DE20541F7EAFE06D0F2451209",
        "dependencies": [],
        "conflicts": [],
        "scope": "ALL 53 skill names+descriptions (Skills.gd) and ALL 60 support names+descriptions (SkillSupports.gd); internal skill keys/IDs and config fields untouched; CODE_PATCH on plaintext sources in 04_recovered",
        "entities": [
            {"kind": "localization_unit", "id": p["unit_id"], "classification": "DISPLAY_SAFE",
             "confidence": "INFERENCE_HIGH",
             "expected_runtime_effect": f"displays {p['translation']}"}
            for p in patches
        ],
        "patches": patches,
        "asset_overlays": [],
        "tests": [
            "locked_units_and_preimages",
            "exact_unit_application",
            "resource_contract",
            "declared_delta",
            "compiled_script_load",
            "pck_checksum",
            "exe_structure",
            "pck_roundtrip",
            "boot",
            "phase_checkpoint_skills_tree_zhcn",
        ],
        "not_proven": "visual layout quality, persistence, gameplay, broad localization, or release readiness",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"manifest written: {OUT}")
    print(f"units: {len(patches)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
