extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "do_impl_more_physical_damage", 
												"stat": "physical_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_more_cold_damage", 
												"stat": "cold_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_more_fire_damage", 
												"stat": "fire_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_more_lightning_damage", 
												"stat": "lightning_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_more_toxic_damage", 
												"stat": "toxic_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_more_dot", 
												"stat": "dot_damage", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.07, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 

								{
												"id": "do_impl_damage_per_25_con", 
												"stat": "fire_per_25_constitution", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 1.8, 
												"stepified": 1, 
												"tiers": 4, 
												"weight": 10, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_damage_per_25_str", 
												"stat": "physical_per_25_strength", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 1.8, 
												"stepified": 1, 
												"tiers": 4, 
												"weight": 10, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_damage_per_25_fin", 
												"stat": "toxic_per_25_finesse", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 1.8, 
												"stepified": 1, 
												"tiers": 4, 
												"weight": 10, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_damage_per_25_agi", 
												"stat": "lightning_per_25_agility", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 1.8, 
												"stepified": 1, 
												"tiers": 4, 
												"weight": 10, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_impl_damage_per_25_wis", 
												"stat": "cold_per_25_wisdom", 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 1.8, 
												"stepified": 1, 
												"tiers": 4, 
												"weight": 10, 
												"unique": false, 
												"drop_only": true
								}, 

								{
												"id": "do_more_physical_damage", 
												"stat": "physical_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.1, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 5, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_more_lightning_damage", 
												"stat": "lightning_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.1, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 5, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_more_cold_damage", 
												"stat": "cold_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.1, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 5, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_more_fire_damage", 
												"stat": "fire_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.1, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 5, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_more_toxic_damage", 
												"stat": "toxic_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.1, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 5, 
												"unique": false, 
												"drop_only": true
								}, 


								{
												"id": "do_physical_ailment_effect", 
												"stat": "physical_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_lightning_ailment_effect", 
												"stat": "lightning_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_cold_ailment_effect", 
												"stat": "cold_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_fire_ailment_effect", 
												"stat": "fire_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_toxic_ailment_effect", 
												"stat": "toxic_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.25, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_cast_speed", 
												"stat": "cast_speed", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.4, 
												"step": 1.25, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_crit_chance_flat", 
												"stat": "crit_chance", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 1.5, 
												"stepified": 0.001, 
												"tiers": 3, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_crit_multi", 
												"stat": "crit_multi", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.4, 
												"step": 1.25, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_crit_chance_percent", 
												"stat": "crit_chance", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.85, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 50, 
												"unique": false, 
												"drop_only": true
								}, 
				]
