extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "do_inc_more_cast_speed", 
												"stat": "cast_speed", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_physical_ailment_effect", 
												"stat": "physical_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.1, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_lightning_ailment_effect", 
												"stat": "lightning_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.1, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_cold_ailment_effect", 
												"stat": "cold_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.1, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_fire_ailment_effect", 
												"stat": "fire_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.1, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_toxic_ailment_effect", 
												"stat": "toxic_ailment_effect", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.1, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 25, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_constitution", 
												"stat": "constitution", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.07, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_str", 
												"stat": "strength", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_wisdom", 
												"stat": "wisdom", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_finesse", 
												"stat": "finesse", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_agility", 
												"stat": "agility", 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 

								{
												"id": "do_inc_more_physical_damage", 
												"stat": "physical_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_more_lightning_damage", 
												"stat": "lightning_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_more_cold_damage", 
												"stat": "cold_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_more_fire_damage", 
												"stat": "fire_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
								{
												"id": "do_inc_more_toxic_damage", 
												"stat": "toxic_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": 0.03, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
												"drop_only": true
								}, 
				]

				compile(true)
