extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								
								{
												"id": "do_health_max_flat", 
												"stat": "health_max", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 120, 
												"step": 1.2, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_mitigation_percent", 
												"stat": "mitigation", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.5, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_strength", 
												"stat": "strength", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 80, 
												"step": 1.5, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_constitution", 
												"stat": "constitution", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 80, 
												"step": 1.5, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_agility", 
												"stat": "agility", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 80, 
												"step": 1.5, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_wisdom", 
												"stat": "wisdom", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 80, 
												"step": 1.5, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_finesse", 
												"stat": "finesse", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 80, 
												"step": 1.5, 
												"stepified": 1, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 

								
								{
												"id": "do_physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.7, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.7, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.7, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.7, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "do_toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.7, 
												"step": 1.2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 100, 
												"unique": false, 
								}, 
				]
