extends Node

var monster_stats = {
				MonsterTypes.MonsterType.TRAINING_DUMMY: {
								"name": "Training Dummy", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.PHYSICAL, 
								"attack_range": 50, 
								"attack_time": 0.6, 
								"attack_delay": 0.7, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 1000000000000, 
												"movement_speed": 65.0, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETON_ARCHER: {
								"name": "Skeleton Archer", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.PHYSICAL, 
								"attack_range": 50, 
								"attack_time": 0.6, 
								"attack_delay": 0.7, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 5.0, 
												"movement_speed": 65.0, 
												"cast_speed": 0.5, 
												"physical_ailment_chance": 0.75, 
								}
				}, 
				MonsterTypes.MonsterType.NINJA: {
								"name": "Dark Ninja", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.PHYSICAL, 
								"attack_range": 50, 
								"attack_time": 0.6, 
								"attack_delay": 0.7, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 5.0, 
												"movement_speed": 80.0, 
												"cast_speed": 1.5, 
												"projectile_speed": 2.0, 
												"physical_ailment_chance": 1.0, 
												"physical_ailment_effect": 5.0, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETON_CURSER: {
								"name": "Skeleton Hexer", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.PHYSICAL, 
								"attack_range": 50, 
								"attack_time": 0.6, 
								"attack_delay": 0.7, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 5.0, 
												"movement_speed": 65.0, 
												"cast_speed": 2.0, 
												"physical_ailment_chance": 0.75, 
												"curse_effect": 0.5, 
								}
				}, 
				MonsterTypes.MonsterType.ICE_GOLEM: {
								"name": "Ice Golem", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.COLD, 
								"attack_range": 50, 
								"attack_time": 0.6, 
								"attack_delay": 0.7, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 5.0, 
												"movement_speed": 65.0, 
												"cast_speed": 0.5, 
								}
				}, 
				MonsterTypes.MonsterType.ATTACK_DOG: {
								"name": "Attack Dog", 
								"damage": 9, 
								"damage_type": SkillTags.Tags.TOXIC, 
								"attack_range": 65, 
								"attack_time": 0.8, 
								"attack_delay": 0.9, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 6.0, 
												"movement_speed": 75.0, 
												"crit_chance": 0.25, 
												"crit_multi": 2.5, 
												"toxic_ailment_chance": 0.75, 
												"toxic_ailment_effect": 1.0, 
								}
				}, 
				MonsterTypes.MonsterType.LIGHTNING_DOG: {
								"name": "Shock Dog", 
								"damage": 9, 
								"damage_type": SkillTags.Tags.LIGHTNING, 
								"attack_range": 80, 
								"attack_time": 0.7, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 6.0, 
												"movement_speed": 85.0, 
												"crit_chance": 0.25, 
												"crit_multi": 2.5, 
												"lightning_ailment_chance": 1.0, 
												"lightning_ailment_effect": 1.0, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETON_WARRIOR: {
								"name": "Skeleton Assassin", 
								"damage": 7, 
								"damage_type": SkillTags.Tags.COLD, 
								"attack_range": 80, 
								"attack_time": 0.4, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 3.0, 
												"movement_speed": 65.0, 
												"cold_ailment_chance": 0.75, 
												"cold_ailment_effect": 1.0, 
								}
				}, 
				MonsterTypes.MonsterType.CHILLED_BONES: {
								"name": "Chilly Bones", 
								"damage": 9, 
								"damage_type": SkillTags.Tags.COLD, 
								"attack_range": 65, 
								"attack_time": 0.4, 
								"attack_delay": 0.4, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 2.0, 
												"movement_speed": 60.0, 
												"cold_ailment_chance": 1, 
												"cold_ailment_effect": 1.0, 
												"cold_resistance": 0.9, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETON_MAGE: {
								"name": "Skeleton Mage", 
								"damage": 7, 
								"damage_type": SkillTags.Tags.FIRE, 
								"attack_range": 50, 
								"attack_time": 0.4, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 3.0, 
												"movement_speed": 65.0, 
												"fire_ailment_chance": 1.0, 
												"fire_resistance": 0.9, 
								}
				}, 
				MonsterTypes.MonsterType.FIRE_BOMBER: {
								"name": "Fire Bomber", 
								"damage": 7, 
								"damage_type": SkillTags.Tags.FIRE, 
								"attack_range": 50, 
								"attack_time": 0.4, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 3.0, 
												"movement_speed": 65.0, 
												"fire_ailment_chance": 1.0, 
												"fire_resistance": 0.9, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETON_SPARKER: {
								"name": "Skeleton Sparker", 
								"damage": 7, 
								"damage_type": SkillTags.Tags.LIGHTNING, 
								"attack_range": 50, 
								"attack_time": 0.4, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 3.0, 
												"movement_speed": 65.0, 
												"lightning_ailment_chance": 1.0, 
												"lightning_resistance": 0.9, 
								}
				}, 
				MonsterTypes.MonsterType.ZOMBIE: {
								"name": "Zombie", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.TOXIC, 
								"attack_range": 50, 
								"attack_time": 0.7, 
								"attack_delay": 0.9, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 7.0, 
												"movement_speed": 65.0, 
												"toxic_ailment_chance": 0.5, 
								}
				}, 
				MonsterTypes.MonsterType.SPIDER: {
								"name": "Spider", 
								"damage": 5, 
								"damage_type": SkillTags.Tags.TOXIC, 
								"attack_range": 90, 
								"attack_time": 0.5, 
								"attack_delay": 0.9, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 7.0, 
												"movement_speed": 75.0, 
												"toxic_ailment_chance": 0.75, 
												"toxic_ailment_effect": 2.5, 
								}
				}, 
				MonsterTypes.MonsterType.SKELETOR: {
								"name": "Skeletor", 
								"damage": 15, 
								"damage_type": SkillTags.Tags.PHYSICAL, 
								"attack_range": 80, 
								"attack_time": 0.4, 
								"attack_delay": 0.5, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 5.0, 
												"movement_speed": 80.0, 
												"physical_ailment_chance": 0.5, 
												"block_chance": 0.3, 
								}
				}, 
				MonsterTypes.MonsterType.BOSS_GATEKEEPER: {
								"name": "The Gatekeeper", 
								"damage": 50, 
								"damage_type": SkillTags.Tags.TOXIC, 
								"attack_range": 80, 
								"attack_time": 0.3, 
								"attack_delay": 0.3, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 500.0, 
												"movement_speed": 80.0, 
												"toxic_ailment_chance": 0.5, 
												"physical_resistance": 0.6, 
												"lightning_resistance": 0.6, 
												"cold_resistance": 0.6, 
												"fire_resistance": 0.6, 
												"toxic_resistance": 0.6, 
								}
				}, 
				MonsterTypes.MonsterType.BOSS_SLUDGE: {
								"name": "Sludge", 
								"damage": 35, 
								"damage_type": SkillTags.Tags.TOXIC, 
								"attack_range": 100, 
								"attack_time": 0.9, 
								"attack_delay": 0.8, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 1400.0, 
												"movement_speed": 60.0, 
												"toxic_ailment_chance": 0.5, 
												"physical_resistance": 0.6, 
												"lightning_resistance": 0.6, 
												"cold_resistance": 0.6, 
												"fire_resistance": 0.6, 
												"toxic_resistance": 0.6, 
								}
				}, 
				MonsterTypes.MonsterType.BOSS_SPIRIT_OF_THE_ANCIENT: {
								"name": "Spirit of the Ancients", 
								"damage": 80, 
								"damage_type": SkillTags.Tags.FIRE, 
								"attack_range": 100, 
								"attack_time": 0.9, 
								"attack_delay": 0.8, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 2500.0, 
												"movement_speed": 80.0, 
												"fire_ailment_chance": 0.5, 
												"fire_ailment_effect": 1.5, 
												"physical_resistance": 0.6, 
												"lightning_resistance": 0.6, 
												"cold_resistance": 0.6, 
												"fire_resistance": 0.75, 
												"toxic_resistance": 0.6, 
								}
				}, 
				MonsterTypes.MonsterType.BOSS_MUTATED_SPIDER: {
								"name": "Mutated Spider", 
								"damage": 80, 
								"damage_type": SkillTags.Tags.COLD, 
								"attack_range": 100, 
								"attack_time": 0.7, 
								"attack_delay": 0.6, 
								"xp": 1, 
								"min_lifetime": 60, 
								"stat_overrides": {
												"health_max": 2500.0, 
												"movement_speed": 120.0, 
												"cold_ailment_chance": 0.5, 
												"cold_ailment_effect": 1.5, 
												"physical_resistance": 0.6, 
												"lightning_resistance": 0.6, 
												"cold_resistance": 0.6, 
												"fire_resistance": 0.75, 
												"toxic_resistance": 0.6, 
								}
				}, 
}


