extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "health_max_flat", 
												"stat": "health_max", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 8, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "strength", 
												"stat": "strength", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "constitution", 
												"stat": "constitution", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "agility", 
												"stat": "agility", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "wisdom", 
												"stat": "wisdom", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "finesse", 
												"stat": "finesse", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "health_regen", 
												"stat": "health_regen", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 10, 
												"step": 1.6, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "health_regen_percent", 
												"stat": "health_regen_percent", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.005, 
												"step": 1.5, 
												"stepified": 0.001, 
												"tiers": 4, 
												"weight": 50, 
												"unique": false, 
								}, 
				]
