extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "health_max_flat", 
												"stat": "health_max", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 1000, 
												"unique": false, 
								}, 
								{
												"id": "strength", 
												"stat": "strength", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "constitution", 
												"stat": "constitution", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "agility", 
												"stat": "agility", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "wisdom", 
												"stat": "wisdom", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "finesse", 
												"stat": "finesse", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "vulnerable_effect", 
												"stat": "vulnerable_effect", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "exposure_effect", 
												"stat": "exposure_effect", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "curse_effect", 
												"stat": "curse_effect", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.03, 
												"step": 2.0, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "flat_physical_damage", 
												"stat": "physical_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 2.0, 
												"stepified": 1, 
												"tiers": 6, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "flat_lightning_damage", 
												"stat": "lightning_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 2.0, 
												"stepified": 1, 
												"tiers": 6, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "flat_cold_damage", 
												"stat": "cold_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 2.0, 
												"stepified": 1, 
												"tiers": 6, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "flat_fire_damage", 
												"stat": "fire_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 2.0, 
												"stepified": 1, 
												"tiers": 6, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "flat_toxic_damage", 
												"stat": "toxic_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 1, 
												"step": 2.0, 
												"stepified": 1, 
												"tiers": 6, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "pct_physical_damage", 
												"stat": "physical_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 200, 
												"unique": false, 
								}, 
								{
												"id": "pct_lightning_damage", 
												"stat": "lightning_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 200, 
												"unique": false, 
								}, 
								{
												"id": "pct_cold_damage", 
												"stat": "cold_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 200, 
												"unique": false, 
								}, 
								{
												"id": "pct_fire_damage", 
												"stat": "fire_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 200, 
												"unique": false, 
								}, 
								{
												"id": "pct_toxic_damage", 
												"stat": "toxic_damage", 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 200, 
												"unique": false, 
								}, 
								{
												"id": "physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "projectile_speed", 
												"stat": "projectile_speed", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "area_of_effect", 
												"stat": "area_of_effect", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 2, 
												"weight": 100, 
												"unique": false, 
								}, 
								{
												"id": "incoming_damage", 
												"stat": "incoming_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.MORE, 
												"min_value": - 0.04, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 
								{
												"id": "maximum_physical_resistance", 
												"stat": "maximum_physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 
								{
												"id": "maximum_lightning_resistance", 
												"stat": "maximum_lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 
								{
												"id": "maximum_cold_resistance", 
												"stat": "maximum_cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 
								{
												"id": "maximum_fire_resistance", 
												"stat": "maximum_fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 
								{
												"id": "maximum_toxic_resistance", 
												"stat": "maximum_toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.01, 
												"step": 2, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 5, 
												"unique": false, 
								}, 

				]
