extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "cast_speed", 
												"stat": "cast_speed", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.05, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 6, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "strength", 
												"stat": "strength", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "constitution", 
												"stat": "constitution", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "agility", 
												"stat": "agility", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "wisdom", 
												"stat": "wisdom", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "finesse", 
												"stat": "finesse", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 

								{
												"id": "physical_damage_percent", 
												"stat": "physical_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
												"group_id": "percent_damage"
								}, 
								{
												"id": "lightning_damage_percent", 
												"stat": "lightning_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
												"group_id": "percent_damage"
								}, 
								{
												"id": "cold_damage_percent", 
												"stat": "cold_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
												"group_id": "percent_damage"
								}, 
								{
												"id": "fire_damage_percent", 
												"stat": "fire_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
												"group_id": "percent_damage"
								}, 
								{
												"id": "toxic_damage_percent", 
												"stat": "toxic_damage", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 7, 
												"weight": 250, 
												"unique": false, 
												"group_id": "percent_damage"
								}, 

								{
												"id": "physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "physical_ailment_chance", 
												"stat": "physical_ailment_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.1, 
												"step": 2.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "lightning_ailment_chance", 
												"stat": "lightning_ailment_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.1, 
												"step": 2.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "cold_ailment_chance", 
												"stat": "cold_ailment_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.1, 
												"step": 2.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "fire_ailment_chance", 
												"stat": "fire_ailment_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.1, 
												"step": 2.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "toxic_ailment_chance", 
												"stat": "toxic_ailment_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.1, 
												"step": 2.5, 
												"stepified": 0.01, 
												"tiers": 1, 
												"weight": 250, 
												"unique": false, 
								}, 
				]
