extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "health_max_flat", 
												"stat": "health_max", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 8, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 

								{
												"id": "block_chance", 
												"stat": "block_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.05, 
												"step": 1.3, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "strength", 
												"stat": "strength", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "constitution", 
												"stat": "constitution", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "agility", 
												"stat": "agility", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "wisdom", 
												"stat": "wisdom", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "finesse", 
												"stat": "finesse", 
												"tags": [], 
												"affix_type": Constants.ModType.PREFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.4, 
												"stepified": 1, 
												"tiers": 8, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "crit_chance", 
												"stat": "crit_chance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
												"group_id": "crit_chance"
								}, 
								{
												"id": "crit_chance_attacks", 
												"stat": "crit_chance", 
												"tags": [SkillTags.Tags.ATTACK], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
												"group_id": "crit_chance"
								}, 
								{
												"id": "crit_chance_spells", 
												"stat": "crit_chance", 
												"tags": [SkillTags.Tags.SPELL], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.15, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
												"group_id": "crit_chance"
								}, 
								{
												"id": "crit_multi", 
												"stat": "crit_multi", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 4, 
												"weight": 250, 
												"unique": false, 
												"group_id": "crit_chance"
								}, 
								{
												"id": "cast_speed", 
												"stat": "cast_speed", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.PERCENT, 
												"min_value": 0.08, 
												"step": 1.5, 
												"stepified": 0.01, 
												"tiers": 3, 
												"weight": 50, 
												"unique": false, 
												"group_id": "cast_speed"
								}, 
								{
												"id": "physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "life_gain_on_block", 
												"stat": "life_gain_on_block", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 5, 
												"step": 1.6, 
												"stepified": 1, 
												"tiers": 10, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "health_regen", 
												"stat": "health_regen", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 10, 
												"step": 1.6, 
												"stepified": 1, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "health_regen_percent", 
												"stat": "health_regen_percent", 
												"tags": [], 
												"affix_type": Constants.ModType.SUFFIX, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.005, 
												"step": 1.5, 
												"stepified": 0.001, 
												"tiers": 4, 
												"weight": 50, 
												"unique": false, 
								}, 
				]
