extends GeneMods

func _ready() -> void :
				mod_option_configs = [
								{
												"id": "impl_physical_resistance", 
												"stat": "physical_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_lightning_resistance", 
												"stat": "lightning_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_cold_resistance", 
												"stat": "cold_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_fire_resistance", 
												"stat": "fire_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 
								{
												"id": "impl_toxic_resistance", 
												"stat": "toxic_resistance", 
												"tags": [], 
												"affix_type": Constants.ModType.IMPLICIT, 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.09, 
												"step": 1.4, 
												"stepified": 0.01, 
												"tiers": 5, 
												"weight": 250, 
												"unique": false, 
								}, 


								
								{
												"id": "mercurial_venom_added_lightning_damage", 
												"stat": "lightning_damage", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 35, 
												"step": 2.0, 
												"stepified": 1.0, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "mercurial_venom_added_toxic_damage", 
												"stat": "toxic_damage", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 35, 
												"step": 2.0, 
												"stepified": 1.0, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "mercurial_venom_lightning_chance", 
												"stat": "lightning_ailment_chance", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.15, 
												"step": 2.0, 
												"stepified": 0.1, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "mercurial_venom_toxic_chance", 
												"stat": "toxic_ailment_chance", 
												"type": Constants.ScalingType.FLAT, 
												"min_value": 0.15, 
												"step": 2.0, 
												"stepified": 0.1, 
												"tiers": 1, 
												"weight": 0, 
												"unique": true, 
								}, 
								{
												"id": "mercurial_venom_penetration", 
												"keystone": "UNIQUE_MERCURIAL_VENOM", 
												"weight": 0, 
												"unique": true, 
								}, 
				]

				
				mod_option_configs.append_array(
								CommonRingMods.mod_option_configs.duplicate(true)
				)
				compile()
